//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Managers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.ExpenseTransactions = new HashSet<ExpenseTransaction>();
            this.IncomeTransactions = new HashSet<IncomeTransaction>();
        }
    
        public int AccountId { get; set; }
        public string Name { get; set; }
        public string Bank { get; set; }
        public string AccountNum { get; set; }
        public decimal Balance { get; set; }
        public int AccountTypeId { get; set; }
        public string CurrencyCountry { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseTransaction> ExpenseTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomeTransaction> IncomeTransactions { get; set; }
    }
}
