//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Managers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public int AccountId { get; set; }
        public int TransactionType { get; set; }
        public Nullable<int> IncomeTransactionId { get; set; }
        public Nullable<int> ExpenseTransactionId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ExpenseTransaction ExpenseTransaction { get; set; }
        public virtual IncomeTransaction IncomeTransaction { get; set; }
    }
}
